/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Others;

import Sales.Sales_Finishing_Frame;
import MyConn.MyConn;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.Time;
import java.util.Date;
import java.util.Vector;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import mobile_phone_shop.Default_Frame;

/**
 *
 * @author Samsung Pc
 */
public class Pos_System_Frame extends javax.swing.JPanel {

    Timer t = new Timer(1000, new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {
            java.util.Date date = new java.util.Date();
            time_Hours.setText(date.getHours() + "");
            time_Minitues.setText(date.getMinutes() + "");
            time_Seconds.setText(date.getSeconds() + "");
        }
    });

    public String cashier_ID;
    public Date date;
    public Time time;

    /**
     * Creates new form Pos_System_Frame
     */
    public Pos_System_Frame() {
        initComponents();
        try {
            int id = 0;
            ResultSet getID = MyConn.search("select sale_invoice from sales_details order by sale_invoice desc limit 1");
            while (getID.next()) {
                id = getID.getInt(1);
            }
            invoice.setText(id + 1 + "");
            ResultSet getItems = MyConn.search("select item_code,item_name from items ");
            Vector v = new Vector();
            while (getItems.next()) {
                v.add(getItems.getString(1) + " - " + getItems.getString(2));
            }
            item_List.setListData(v);
            ResultSet getRepairs = MyConn.search("select repair_id,repair_name from repairs_details ");
            Vector v1 = new Vector();
            while (getRepairs.next()) {
                v1.add(getRepairs.getString(1) + " - " + getRepairs.getString(2));
            }
            repair_List.setListData(v1);
            ResultSet getCashiers = MyConn.search("select * from staff_members where is_active = 1 ");
            while (getCashiers.next()) {
                cashier.addItem(getCashiers.getString(1) + " - " + getCashiers.getString(2) + " " + getCashiers.getString(3));
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Item_Selecting_Panel = new javax.swing.JPanel();
        item_Name = new javax.swing.JTextField();
        jScroolPane12 = new javax.swing.JScrollPane();
        item_List = new javax.swing.JList<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        item_Barcode = new javax.swing.JTextField();
        item_Count = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stock_Table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        item_Price = new javax.swing.JTextField();
        add_Item_to_Cart = new javax.swing.JButton();
        remove_Item_from_Cart = new javax.swing.JButton();
        repairs_Selecting_Panel = new javax.swing.JPanel();
        repair_Name = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        repair_List = new javax.swing.JList<>();
        add_Repair_to_Cart = new javax.swing.JButton();
        remove_Repair_from_Cart = new javax.swing.JButton();
        reapir_Price = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        repair_Barcode = new javax.swing.JTextField();
        repair_Count = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cart_Table = new javax.swing.JTable();
        finish_This_Sale = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        sub_Total = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        discount = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        grand_Total = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        invoice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        invoice_Date = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        time_Hours = new javax.swing.JTextField();
        time_Minitues = new javax.swing.JTextField();
        time_Seconds = new javax.swing.JTextField();
        now = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cashier = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Add to Cart"));

        Item_Selecting_Panel.setBackground(new java.awt.Color(255, 255, 255));

        item_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                item_NameKeyReleased(evt);
            }
        });

        jScroolPane12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        item_List.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item_ListMouseClicked(evt);
            }
        });
        jScroolPane12.setViewportView(item_List);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Bar Code");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText(":");

        item_Barcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item_Barcode.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                item_BarcodeInputMethodTextChanged(evt);
            }
        });
        item_Barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_BarcodeActionPerformed(evt);
            }
        });

        item_Count.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item_Count.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                item_CountKeyReleased(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText(":");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Count");

        stock_Table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stock_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock ID", "Color", "Size", "Selling Price", "No In Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stock_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stock_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stock_Table);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Total Price");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(":");

        item_Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item_Price.setEnabled(false);
        item_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_PriceActionPerformed(evt);
            }
        });

        add_Item_to_Cart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add_Item_to_Cart.setText("Add To Cart");
        add_Item_to_Cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_Item_to_CartActionPerformed(evt);
            }
        });

        remove_Item_from_Cart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        remove_Item_from_Cart.setText("Remove from Cart");
        remove_Item_from_Cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_Item_from_CartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Item_Selecting_PanelLayout = new javax.swing.GroupLayout(Item_Selecting_Panel);
        Item_Selecting_Panel.setLayout(Item_Selecting_PanelLayout);
        Item_Selecting_PanelLayout.setHorizontalGroup(
            Item_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_Selecting_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Item_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(item_Name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScroolPane12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Item_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Item_Selecting_PanelLayout.createSequentialGroup()
                        .addGroup(Item_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Item_Selecting_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Item_Selecting_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(Item_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Item_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item_Barcode)
                            .addComponent(item_Count, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(Item_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Item_Selecting_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(item_Price, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                            .addGroup(Item_Selecting_PanelLayout.createSequentialGroup()
                                .addComponent(add_Item_to_Cart, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(remove_Item_from_Cart, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        Item_Selecting_PanelLayout.setVerticalGroup(
            Item_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_Selecting_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Item_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Item_Selecting_PanelLayout.createSequentialGroup()
                        .addComponent(item_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScroolPane12))
                    .addGroup(Item_Selecting_PanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Item_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Item_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Item_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(item_Price)
                                .addComponent(item_Barcode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Item_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Item_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_Item_to_Cart)
                            .addComponent(remove_Item_from_Cart))))
                .addContainerGap())
        );

        Item_Selecting_PanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {add_Item_to_Cart, item_Barcode, item_Count, item_Name, item_Price, remove_Item_from_Cart});

        jTabbedPane1.addTab("Items", Item_Selecting_Panel);

        repairs_Selecting_Panel.setBackground(new java.awt.Color(255, 255, 255));

        repair_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        repair_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                repair_NameKeyReleased(evt);
            }
        });

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        repair_List.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(repair_List);

        add_Repair_to_Cart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add_Repair_to_Cart.setText("Add To Cart");
        add_Repair_to_Cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_Repair_to_CartActionPerformed(evt);
            }
        });

        remove_Repair_from_Cart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        remove_Repair_from_Cart.setText("Remove from Cart");
        remove_Repair_from_Cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_Repair_from_CartActionPerformed(evt);
            }
        });

        reapir_Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reapir_Price.setEnabled(false);
        reapir_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reapir_PriceActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Price");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText(":");

        repair_Barcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        repair_Barcode.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                repair_BarcodeInputMethodTextChanged(evt);
            }
        });
        repair_Barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repair_BarcodeActionPerformed(evt);
            }
        });

        repair_Count.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        repair_Count.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                repair_CountInputMethodTextChanged(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText(":");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText(":");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Bar Code");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Count");

        javax.swing.GroupLayout repairs_Selecting_PanelLayout = new javax.swing.GroupLayout(repairs_Selecting_Panel);
        repairs_Selecting_Panel.setLayout(repairs_Selecting_PanelLayout);
        repairs_Selecting_PanelLayout.setHorizontalGroup(
            repairs_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repairs_Selecting_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(repairs_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(repairs_Selecting_PanelLayout.createSequentialGroup()
                        .addComponent(repair_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(repairs_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29))
                        .addGap(4, 4, 4)
                        .addGroup(repairs_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(repairs_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(repair_Barcode)
                            .addComponent(repair_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reapir_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(repairs_Selecting_PanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(356, 356, 356)
                        .addGroup(repairs_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_Repair_to_Cart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(remove_Repair_from_Cart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        repairs_Selecting_PanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane2, repair_Name});

        repairs_Selecting_PanelLayout.setVerticalGroup(
            repairs_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repairs_Selecting_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(repairs_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(repairs_Selecting_PanelLayout.createSequentialGroup()
                        .addComponent(repair_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(repairs_Selecting_PanelLayout.createSequentialGroup()
                        .addGroup(repairs_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(repairs_Selecting_PanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(reapir_Price))
                            .addGroup(repairs_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(repair_Barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(repairs_Selecting_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(repair_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_Repair_to_Cart)
                        .addGap(10, 10, 10)
                        .addComponent(remove_Repair_from_Cart)
                        .addGap(21, 21, 21))))
        );

        jTabbedPane1.addTab("Repairs", repairs_Selecting_Panel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1)
                .addGap(6, 6, 6))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cart"));

        cart_Table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cart_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item or Repair", "Item / Repair", "Selling Price", "Count", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cart_Table.setRowHeight(25);
        jScrollPane3.setViewportView(cart_Table);

        finish_This_Sale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finish_This_Sale.setText("Finish This Deal");
        finish_This_Sale.setActionCommand("Finish This Sale");
        finish_This_Sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finish_This_SaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(finish_This_Sale, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finish_This_Sale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Payments"));

        sub_Total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sub_Total.setEnabled(false);
        sub_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_TotalActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(":");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Sub Total");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Discount");

        discount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(":");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(":");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Grand Total");

        grand_Total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        grand_Total.setEnabled(false);
        grand_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grand_TotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(grand_Total, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(discount)
                    .addComponent(sub_Total))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel12, jLabel13, jLabel16});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grand_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {discount, grand_Total, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel16, sub_Total});

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sale Details"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Invoice");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(":");

        invoice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        invoice.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(":");

        invoice_Date.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Time");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(":");

        time_Hours.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        time_Minitues.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        time_Seconds.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        now.setBackground(new java.awt.Color(255, 255, 255));
        now.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        now.setText("Now");
        now.setFocusable(false);
        now.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nowActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Cashier");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(":");

        cashier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invoice))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invoice_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(time_Hours, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(time_Minitues, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(time_Seconds, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(now, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cashier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {time_Hours, time_Minitues, time_Seconds});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel3, jLabel5, jLabel7});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoice_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(time_Seconds)
                    .addComponent(time_Hours)
                    .addComponent(time_Minitues))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(now, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cashier, invoice, jLabel1, jLabel2, jLabel7, jLabel8});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel5, time_Hours, time_Minitues, time_Seconds});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nowActionPerformed
        if (now.isSelected()) {
            t.start();
            invoice_Date.setEnabled(false);
            time_Hours.setEnabled(false);
            time_Minitues.setEnabled(false);
            time_Seconds.setEnabled(false);
        } else {
            t.stop();
            time_Hours.setEnabled(true);
            invoice_Date.setEnabled(true);
            time_Minitues.setEnabled(true);
            time_Seconds.setEnabled(true);
            time_Hours.setText(null);
            time_Minitues.setText(null);
            time_Seconds.setText(null);
        }
    }//GEN-LAST:event_nowActionPerformed

    private void item_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_PriceActionPerformed

    private void sub_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_TotalActionPerformed

    private void discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountActionPerformed

    private void grand_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grand_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grand_TotalActionPerformed

    private void item_BarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_BarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_BarcodeActionPerformed

    private void repair_BarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repair_BarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repair_BarcodeActionPerformed

    private void reapir_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reapir_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reapir_PriceActionPerformed

    private void add_Item_to_CartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_Item_to_CartActionPerformed
        DefaultTableModel df = (DefaultTableModel) cart_Table.getModel();
        Vector v = new Vector();
        v.add("Item");
        v.add(stock_Table.getValueAt(stock_Table.getSelectedRow(), 0).toString().split(" - ")[0] + " - " + repair_List.getSelectedValue().split(" - ")[1]);
        v.add(stock_Table.getValueAt(stock_Table.getSelectedRow(), 3).toString());
        v.add(item_Count.getText());
        v.add(item_Price.getText());
        df.addRow(v);
    }//GEN-LAST:event_add_Item_to_CartActionPerformed

    private void item_ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item_ListMouseClicked
        try {
            ResultSet rs = MyConn.search("select * from item_stock where item_code = '" + item_List.getSelectedValue().toString().split(" - ")[0] + "' ");
            DefaultTableModel df = (DefaultTableModel) stock_Table.getModel();
            int rowCount = df.getRowCount();
            for (int i = 0; i < rowCount; i++) {
                df.removeRow(0);
            }
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                ResultSet getColro = MyConn.search("select * from item_colors where color_id = '" + rs.getString(3) + "' ");
                while (getColro.next()) {
                    v.add(getColro.getString(1) + " - " + getColro.getString(2));
                }
                ResultSet getSizes = MyConn.search("select * from item_sizes where size_id = '" + rs.getString(4) + "' ");
                while (getSizes.next()) {
                    v.add(getSizes.getString(1) + " - " + getSizes.getString(2));
                }
                v.add(rs.getString(6));
                v.add(rs.getString(7));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_item_ListMouseClicked

    private void remove_Item_from_CartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_Item_from_CartActionPerformed
        DefaultTableModel df = (DefaultTableModel) cart_Table.getModel();
        df.removeRow(cart_Table.getSelectedRow());
    }//GEN-LAST:event_remove_Item_from_CartActionPerformed

    private void stock_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_TableMouseClicked
        item_Price.setText(Double.parseDouble(stock_Table.getValueAt(stock_Table.getSelectedRow(), 3).toString()) * Integer.parseInt(item_Count.getText()) + "");
    }//GEN-LAST:event_stock_TableMouseClicked

    private void item_CountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_item_CountKeyReleased
        item_Price.setText(Double.parseDouble(stock_Table.getValueAt(stock_Table.getSelectedRow(), 3).toString()) * Integer.parseInt(item_Count.getText()) + "");
    }//GEN-LAST:event_item_CountKeyReleased

    private void finish_This_SaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finish_This_SaleActionPerformed
        Sales_Finishing_Frame fr = new Sales_Finishing_Frame();
        fr.setVisible(true);
        fr.cart_Table.setModel(cart_Table.getModel());
        fr.invoice_No.setText(invoice.getText());
        fr.sub_Total.setText(grand_Total.getText());
        fr.date = this.date;
        fr.time = this.time;
        fr.cashier_ID = this.cashier_ID;
    }//GEN-LAST:event_finish_This_SaleActionPerformed

    private void add_Repair_to_CartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_Repair_to_CartActionPerformed
        DefaultTableModel df = (DefaultTableModel) cart_Table.getModel();
        Vector v = new Vector();
        v.add("Repair");
        v.add(item_List.getSelectedValue());
        v.add(Double.parseDouble(reapir_Price.getText()) / Integer.parseInt(repair_Count.getText()));
        v.add(repair_Count.getText());
        v.add(reapir_Price.getText());
        df.addRow(v);
    }//GEN-LAST:event_add_Repair_to_CartActionPerformed

    private void remove_Repair_from_CartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_Repair_from_CartActionPerformed
        DefaultTableModel df = (DefaultTableModel) cart_Table.getModel();
        df.removeRow(cart_Table.getSelectedRow());
    }//GEN-LAST:event_remove_Repair_from_CartActionPerformed

    private void item_NameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_item_NameKeyReleased
        try {
            ResultSet getItems = MyConn.search("select item_code,item_name from items where item_name like '" + item_Name.getText() + "%' ");
            Vector v = new Vector();
            while (getItems.next()) {
                v.add(getItems.getString(1) + " - " + getItems.getString(2));
            }
            item_List.setListData(v);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_item_NameKeyReleased

    private void repair_NameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_repair_NameKeyReleased
        try {
            ResultSet getRepairs = MyConn.search("select repair_id,repair_name from repairs_details where repair_name like '" + repair_Name.getText() + "%'  ");
            Vector v1 = new Vector();
            while (getRepairs.next()) {
                v1.add(getRepairs.getString(1) + " - " + getRepairs.getString(2));
            }
            repair_List.setListData(v1);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_repair_NameKeyReleased

    private void repair_CountInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_repair_CountInputMethodTextChanged
        ////////////////////////////////////////////////////////////////
    }//GEN-LAST:event_repair_CountInputMethodTextChanged

    private void item_BarcodeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_item_BarcodeInputMethodTextChanged
        try {
            ResultSet getItems = MyConn.search("select item_code,item_name from items where item_barcode = '" + item_Name.getText() + "' ");
            Vector v = new Vector();
            while (getItems.next()) {
                v.add(getItems.getString(1) + " - " + getItems.getString(2));
            }
            item_List.setListData(v);
            item_List.setSelectedIndex(0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_item_BarcodeInputMethodTextChanged

    private void repair_BarcodeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_repair_BarcodeInputMethodTextChanged
        try {
            ResultSet getRepairs = MyConn.search("select repair_id,repair_name from repairs_details where repair_barcode = '" + repair_Name.getText() + "'  ");
            Vector v1 = new Vector();
            while (getRepairs.next()) {
                v1.add(getRepairs.getString(1) + " - " + getRepairs.getString(2));
            }
            repair_List.setListData(v1);
            repair_List.setSelectedIndex(0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_repair_BarcodeInputMethodTextChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Item_Selecting_Panel;
    private javax.swing.JButton add_Item_to_Cart;
    private javax.swing.JButton add_Repair_to_Cart;
    private javax.swing.JTable cart_Table;
    private javax.swing.JComboBox<String> cashier;
    private javax.swing.JTextField discount;
    private javax.swing.JButton finish_This_Sale;
    private javax.swing.JTextField grand_Total;
    private javax.swing.JTextField invoice;
    private datechooser.beans.DateChooserCombo invoice_Date;
    private javax.swing.JTextField item_Barcode;
    private javax.swing.JTextField item_Count;
    private javax.swing.JList<String> item_List;
    private javax.swing.JTextField item_Name;
    private javax.swing.JTextField item_Price;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScroolPane12;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox now;
    private javax.swing.JTextField reapir_Price;
    private javax.swing.JButton remove_Item_from_Cart;
    private javax.swing.JButton remove_Repair_from_Cart;
    private javax.swing.JTextField repair_Barcode;
    private javax.swing.JTextField repair_Count;
    private javax.swing.JList<String> repair_List;
    private javax.swing.JTextField repair_Name;
    private javax.swing.JPanel repairs_Selecting_Panel;
    private javax.swing.JTable stock_Table;
    private javax.swing.JTextField sub_Total;
    private javax.swing.JTextField time_Hours;
    private javax.swing.JTextField time_Minitues;
    private javax.swing.JTextField time_Seconds;
    // End of variables declaration//GEN-END:variables
}
