/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main_Frames;

import Items.Add_New_Item;
import Items.Add_New_Phone;
import Others.Categories_Details;
import Others.Colors_Details;
import Others.Companies;
import Others.Item_Sizes;
import Stock.New_GRN_Frame;
import Others.Pos_System_Frame;
import Others.Repairs_Details;
import Staff.Staff_Attending_Details;
import Staff.Staff_Members_Details;
import Staff.Staff_Salary_Paying;
import Stock.Stock_Returns;
import Others.Suppliers_Details;
import Others.Users_Details;
import Items.Items_Details;
import Items.Phone_Details;
import Items.Stock_Frame;
import Sales.Sales_Returns_Details;
import Stock.GRN_Report;
import Sales.Sales_Report;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import com.sun.java.swing.plaf.windows.WindowsScrollPaneUI;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Samsung Pc
 */
public class Main_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Main_Frame
     */
    public Main_Frame() {
        initComponents();

        // Setting Window Screen Size
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Toolkit tk = Toolkit.getDefaultToolkit();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        staff_Img.setIcon(new ImageIcon(tk.getImage(getClass().getResource("/Icons/Staff.png")).getScaledInstance(35, 35, WIDTH)));
        jScrollPane1.updateUI();
        try {
            UIManager.setLookAndFeel(new WindowsLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Main_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }

        item_TaskPane.updateUI();
        other_Task_Pane.updateUI();
        staff_Task_Pane.updateUI();
        sales_task_Pane.updateUI();
        GRN_task_Pane.updateUI();
        jDesktopPane1.requestFocus();
        jScrollPane1.setUI(new WindowsScrollPaneUI());
        
        Stock_Icon.setIcon(new ImageIcon(tk.getImage(getClass().getResource("/Icons/Stock_Icon.png")).getScaledInstance(30, 30, WIDTH)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_Panel = new javax.swing.JPanel();
        menu_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        item_TaskPane = new org.jdesktop.swingx.JXTaskPane();
        Item_Panel = new org.jdesktop.swingx.JXPanel();
        search_Item_Icone = new javax.swing.JLabel();
        add_Item_Icon = new javax.swing.JLabel();
        add_New_Item = new javax.swing.JLabel();
        search_Item = new javax.swing.JLabel();
        add_New_Phone = new javax.swing.JLabel();
        search_Item_Icone1 = new javax.swing.JLabel();
        search_Phones = new javax.swing.JLabel();
        search_Item_Icone7 = new javax.swing.JLabel();
        Stock_Icon = new javax.swing.JLabel();
        Stock_Label = new javax.swing.JLabel();
        sales_task_Pane = new org.jdesktop.swingx.JXTaskPane();
        other_Panel2 = new org.jdesktop.swingx.JXPanel();
        search_Item_Icone8 = new javax.swing.JLabel();
        sales_Report = new javax.swing.JLabel();
        search_Item_Icone9 = new javax.swing.JLabel();
        sales_Returns = new javax.swing.JLabel();
        staff_Img1 = new javax.swing.JLabel();
        pos_System = new javax.swing.JLabel();
        sales_Returns_Details = new javax.swing.JLabel();
        search_Item_Icone12 = new javax.swing.JLabel();
        GRN_task_Pane = new org.jdesktop.swingx.JXTaskPane();
        other_Panel3 = new org.jdesktop.swingx.JXPanel();
        search_Item_Icone10 = new javax.swing.JLabel();
        GRN_Report = new javax.swing.JLabel();
        search_Item_Icone11 = new javax.swing.JLabel();
        stock_Return = new javax.swing.JLabel();
        staff_Img2 = new javax.swing.JLabel();
        add_new_GRN = new javax.swing.JLabel();
        stock_Returns_Details = new javax.swing.JLabel();
        search_Item_Icone13 = new javax.swing.JLabel();
        staff_Task_Pane = new org.jdesktop.swingx.JXTaskPane();
        other_Panel1 = new org.jdesktop.swingx.JXPanel();
        search_Item_Icone5 = new javax.swing.JLabel();
        staff_Attending = new javax.swing.JLabel();
        search_Item_Icone6 = new javax.swing.JLabel();
        srtaff_Salary_Paying = new javax.swing.JLabel();
        staff_Img = new javax.swing.JLabel();
        staff_Details = new javax.swing.JLabel();
        other_Task_Pane = new org.jdesktop.swingx.JXTaskPane();
        other_Panel = new org.jdesktop.swingx.JXPanel();
        categories_Details = new javax.swing.JLabel();
        add_Item_Icon1 = new javax.swing.JLabel();
        search_Item_Icone2 = new javax.swing.JLabel();
        suppliers_Details = new javax.swing.JLabel();
        search_Item_Icone3 = new javax.swing.JLabel();
        companies_Details = new javax.swing.JLabel();
        search_Item_Icone4 = new javax.swing.JLabel();
        colours_Details = new javax.swing.JLabel();
        search_Item_Icone14 = new javax.swing.JLabel();
        users_Details = new javax.swing.JLabel();
        search_Item_Icone15 = new javax.swing.JLabel();
        item_Sizes = new javax.swing.JLabel();
        search_Item_Icone16 = new javax.swing.JLabel();
        repairs_Details = new javax.swing.JLabel();
        content_Panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Frame");
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        main_Panel.setBackground(new java.awt.Color(255, 255, 255));

        menu_Panel.setBackground(new java.awt.Color(255, 255, 255));
        menu_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        menu_Panel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu_Panel.setMaximumSize(new java.awt.Dimension(1280, 768));

        jScrollPane1.setBorder(null);
        jScrollPane1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane1ComponentAdded(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        item_TaskPane.setBackground(new java.awt.Color(51, 102, 255));
        item_TaskPane.setForeground(new java.awt.Color(204, 255, 204));
        item_TaskPane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Items.png"))); // NOI18N
        item_TaskPane.setScrollOnExpand(true);
        item_TaskPane.setTitle("Items");
        item_TaskPane.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        item_TaskPane.setOpaque(true);

        Item_Panel.setBackground(new java.awt.Color(255, 255, 255));

        search_Item_Icone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        search_Item_Icone.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        add_Item_Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add_Item_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add_New_Item.png"))); // NOI18N
        add_Item_Icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        add_New_Item.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add_New_Item.setText("Add New Item");
        add_New_Item.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                add_New_ItemFocusGained(evt);
            }
        });
        add_New_Item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_New_ItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_New_ItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_New_ItemMouseExited(evt);
            }
        });

        search_Item.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        search_Item.setText("Search Item");
        search_Item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_ItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search_ItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search_ItemMouseExited(evt);
            }
        });

        add_New_Phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add_New_Phone.setText("Add New Phone");
        add_New_Phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_New_PhoneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_New_PhoneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_New_PhoneMouseExited(evt);
            }
        });

        search_Item_Icone1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add_New_Phone.png"))); // NOI18N
        search_Item_Icone1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        search_Phones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        search_Phones.setText("Search Phones");
        search_Phones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_PhonesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search_PhonesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search_PhonesMouseExited(evt);
            }
        });

        search_Item_Icone7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        search_Item_Icone7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Stock_Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Stock_Icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Stock_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Stock_Label.setText("Stock");
        Stock_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Stock_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Stock_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Stock_LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Item_PanelLayout = new javax.swing.GroupLayout(Item_Panel);
        Item_Panel.setLayout(Item_PanelLayout);
        Item_PanelLayout.setHorizontalGroup(
            Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_PanelLayout.createSequentialGroup()
                .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add_Item_Icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_Item_Icone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_Item_Icone1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_Item_Icone7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Stock_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_New_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_New_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_Phones, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stock_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        Item_PanelLayout.setVerticalGroup(
            Item_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_PanelLayout.createSequentialGroup()
                .addComponent(add_Item_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(search_Item_Icone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(search_Item_Icone1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(search_Item_Icone7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Stock_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Item_PanelLayout.createSequentialGroup()
                .addComponent(add_New_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(search_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(add_New_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(search_Phones, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Stock_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        item_TaskPane.getContentPane().add(Item_Panel);

        sales_task_Pane.setBackground(new java.awt.Color(102, 153, 255));
        sales_task_Pane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Sales.png"))); // NOI18N
        sales_task_Pane.setTitle("Sales");
        sales_task_Pane.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        other_Panel2.setBackground(new java.awt.Color(255, 255, 255));

        search_Item_Icone8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sales_Report.png"))); // NOI18N
        search_Item_Icone8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        sales_Report.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sales_Report.setText("Sales Report");
        sales_Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sales_ReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sales_ReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sales_ReportMouseExited(evt);
            }
        });

        search_Item_Icone9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Sales_Return.png"))); // NOI18N
        search_Item_Icone9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        sales_Returns.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sales_Returns.setText("Sales Returns");
        sales_Returns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sales_ReturnsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sales_ReturnsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sales_ReturnsMouseExited(evt);
            }
        });

        staff_Img1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staff_Img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/POS.png"))); // NOI18N
        staff_Img1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pos_System.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pos_System.setText("POS System");
        pos_System.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos_SystemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pos_SystemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pos_SystemMouseExited(evt);
            }
        });

        sales_Returns_Details.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sales_Returns_Details.setText("Sales Returns Details");
        sales_Returns_Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sales_Returns_DetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sales_Returns_DetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sales_Returns_DetailsMouseExited(evt);
            }
        });

        search_Item_Icone12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Sales_Returns_Details.png"))); // NOI18N
        search_Item_Icone12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout other_Panel2Layout = new javax.swing.GroupLayout(other_Panel2);
        other_Panel2.setLayout(other_Panel2Layout);
        other_Panel2Layout.setHorizontalGroup(
            other_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(other_Panel2Layout.createSequentialGroup()
                .addGroup(other_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, other_Panel2Layout.createSequentialGroup()
                        .addGroup(other_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(search_Item_Icone8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(search_Item_Icone9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(search_Item_Icone12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(other_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sales_Returns, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sales_Returns_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sales_Report, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, other_Panel2Layout.createSequentialGroup()
                        .addComponent(staff_Img1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pos_System, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        other_Panel2Layout.setVerticalGroup(
            other_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(other_Panel2Layout.createSequentialGroup()
                .addGroup(other_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(other_Panel2Layout.createSequentialGroup()
                        .addComponent(staff_Img1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(search_Item_Icone8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(search_Item_Icone9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(search_Item_Icone12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(other_Panel2Layout.createSequentialGroup()
                        .addComponent(pos_System, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(sales_Report, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(sales_Returns, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(sales_Returns_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        sales_task_Pane.getContentPane().add(other_Panel2);

        GRN_task_Pane.setBackground(new java.awt.Color(102, 153, 255));
        GRN_task_Pane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/GRN_Icon.png"))); // NOI18N
        GRN_task_Pane.setTitle("GRN");
        GRN_task_Pane.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        other_Panel3.setBackground(new java.awt.Color(255, 255, 255));

        search_Item_Icone10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/GRN_Report.png"))); // NOI18N
        search_Item_Icone10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        GRN_Report.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GRN_Report.setText("GRN Report");
        GRN_Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GRN_ReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GRN_ReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GRN_ReportMouseExited(evt);
            }
        });

        search_Item_Icone11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Stock_Return.png"))); // NOI18N
        search_Item_Icone11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        stock_Return.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stock_Return.setText("Stock Returns");
        stock_Return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stock_ReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stock_ReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stock_ReturnMouseExited(evt);
            }
        });

        staff_Img2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staff_Img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/GRN.png"))); // NOI18N
        staff_Img2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        add_new_GRN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add_new_GRN.setText("Add New GRN");
        add_new_GRN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_new_GRNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_new_GRNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_new_GRNMouseExited(evt);
            }
        });

        stock_Returns_Details.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stock_Returns_Details.setText("Stock Returns Details");
        stock_Returns_Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stock_Returns_DetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stock_Returns_DetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stock_Returns_DetailsMouseExited(evt);
            }
        });

        search_Item_Icone13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Stock_Returns_Details.png"))); // NOI18N
        search_Item_Icone13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout other_Panel3Layout = new javax.swing.GroupLayout(other_Panel3);
        other_Panel3.setLayout(other_Panel3Layout);
        other_Panel3Layout.setHorizontalGroup(
            other_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(other_Panel3Layout.createSequentialGroup()
                .addGroup(other_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(other_Panel3Layout.createSequentialGroup()
                        .addGroup(other_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(search_Item_Icone10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(search_Item_Icone11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(search_Item_Icone13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(other_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stock_Returns_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(other_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(stock_Return, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addComponent(GRN_Report, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(other_Panel3Layout.createSequentialGroup()
                        .addComponent(staff_Img2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(add_new_GRN, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        other_Panel3Layout.setVerticalGroup(
            other_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(other_Panel3Layout.createSequentialGroup()
                .addGroup(other_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(other_Panel3Layout.createSequentialGroup()
                        .addComponent(staff_Img2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(search_Item_Icone10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(search_Item_Icone11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(search_Item_Icone13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(other_Panel3Layout.createSequentialGroup()
                        .addComponent(add_new_GRN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(GRN_Report, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(stock_Return, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(stock_Returns_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        GRN_task_Pane.getContentPane().add(other_Panel3);

        staff_Task_Pane.setBackground(new java.awt.Color(102, 153, 255));
        staff_Task_Pane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Staff_Icon.png"))); // NOI18N
        staff_Task_Pane.setTitle("Staff");
        staff_Task_Pane.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        other_Panel1.setBackground(new java.awt.Color(255, 255, 255));

        search_Item_Icone5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Attending.png"))); // NOI18N
        search_Item_Icone5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        staff_Attending.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        staff_Attending.setText("Staff Attending");
        staff_Attending.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staff_AttendingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                staff_AttendingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                staff_AttendingMouseExited(evt);
            }
        });

        search_Item_Icone6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Salary.png"))); // NOI18N
        search_Item_Icone6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        srtaff_Salary_Paying.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        srtaff_Salary_Paying.setText("Staff Salary Paying");
        srtaff_Salary_Paying.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                srtaff_Salary_PayingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                srtaff_Salary_PayingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                srtaff_Salary_PayingMouseExited(evt);
            }
        });

        staff_Img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staff_Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Supplier.png"))); // NOI18N
        staff_Img.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        staff_Details.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        staff_Details.setText("Staff Details");
        staff_Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staff_DetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                staff_DetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                staff_DetailsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout other_Panel1Layout = new javax.swing.GroupLayout(other_Panel1);
        other_Panel1.setLayout(other_Panel1Layout);
        other_Panel1Layout.setHorizontalGroup(
            other_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(other_Panel1Layout.createSequentialGroup()
                .addGroup(other_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(other_Panel1Layout.createSequentialGroup()
                        .addGroup(other_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(search_Item_Icone5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(search_Item_Icone6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(other_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(srtaff_Salary_Paying, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(staff_Attending, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(other_Panel1Layout.createSequentialGroup()
                        .addComponent(staff_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(staff_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        other_Panel1Layout.setVerticalGroup(
            other_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(other_Panel1Layout.createSequentialGroup()
                .addGroup(other_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(other_Panel1Layout.createSequentialGroup()
                        .addComponent(staff_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(search_Item_Icone5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(search_Item_Icone6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(other_Panel1Layout.createSequentialGroup()
                        .addComponent(staff_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(staff_Attending, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(srtaff_Salary_Paying, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        staff_Task_Pane.getContentPane().add(other_Panel1);

        other_Task_Pane.setBackground(new java.awt.Color(102, 153, 255));
        other_Task_Pane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Others.png"))); // NOI18N
        other_Task_Pane.setTitle("Others");
        other_Task_Pane.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        other_Panel.setBackground(new java.awt.Color(255, 255, 255));

        categories_Details.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        categories_Details.setText("Categories Details");
        categories_Details.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                categories_DetailsFocusGained(evt);
            }
        });
        categories_Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categories_DetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categories_DetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                categories_DetailsMouseExited(evt);
            }
        });

        add_Item_Icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add_Item_Icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/categories.png"))); // NOI18N
        add_Item_Icon1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        search_Item_Icone2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Supplier.png"))); // NOI18N
        search_Item_Icone2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        suppliers_Details.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        suppliers_Details.setText("Suppliers Details");
        suppliers_Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suppliers_DetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suppliers_DetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suppliers_DetailsMouseExited(evt);
            }
        });

        search_Item_Icone3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Company.png"))); // NOI18N
        search_Item_Icone3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        companies_Details.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        companies_Details.setText("Companies Details");
        companies_Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companies_DetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                companies_DetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                companies_DetailsMouseExited(evt);
            }
        });

        search_Item_Icone4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Colours.png"))); // NOI18N
        search_Item_Icone4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        colours_Details.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        colours_Details.setText("Colours Details");
        colours_Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colours_DetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colours_DetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colours_DetailsMouseExited(evt);
            }
        });

        search_Item_Icone14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Users.png"))); // NOI18N
        search_Item_Icone14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        users_Details.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        users_Details.setText("Users Details");
        users_Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                users_DetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                users_DetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                users_DetailsMouseExited(evt);
            }
        });

        search_Item_Icone15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Item_Sizes.png"))); // NOI18N
        search_Item_Icone15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        item_Sizes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item_Sizes.setText("Item Size Details");
        item_Sizes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item_SizesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                item_SizesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                item_SizesMouseExited(evt);
            }
        });

        search_Item_Icone16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_Item_Icone16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Repairs.png"))); // NOI18N
        search_Item_Icone16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        repairs_Details.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        repairs_Details.setText("Repairs Details");
        repairs_Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                repairs_DetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                repairs_DetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                repairs_DetailsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout other_PanelLayout = new javax.swing.GroupLayout(other_Panel);
        other_Panel.setLayout(other_PanelLayout);
        other_PanelLayout.setHorizontalGroup(
            other_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(other_PanelLayout.createSequentialGroup()
                .addGroup(other_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add_Item_Icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(search_Item_Icone2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_Item_Icone3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_Item_Icone4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_Item_Icone14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_Item_Icone15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_Item_Icone16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(other_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categories_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suppliers_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companies_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colours_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(users_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item_Sizes, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repairs_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        other_PanelLayout.setVerticalGroup(
            other_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(other_PanelLayout.createSequentialGroup()
                .addComponent(add_Item_Icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(search_Item_Icone2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(search_Item_Icone3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(search_Item_Icone4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(search_Item_Icone14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(search_Item_Icone15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(search_Item_Icone16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(other_PanelLayout.createSequentialGroup()
                .addComponent(categories_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(suppliers_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(companies_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(colours_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(users_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(item_Sizes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(repairs_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        other_Task_Pane.getContentPane().add(other_Panel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(item_TaskPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staff_Task_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(GRN_task_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(sales_task_Pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(other_Task_Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(item_TaskPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sales_task_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GRN_task_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staff_Task_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(other_Task_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout menu_PanelLayout = new javax.swing.GroupLayout(menu_Panel);
        menu_Panel.setLayout(menu_PanelLayout);
        menu_PanelLayout.setHorizontalGroup(
            menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_PanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menu_PanelLayout.setVerticalGroup(
            menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );

        content_Panel.setBackground(new java.awt.Color(255, 255, 255));
        content_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Content", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        content_Panel.setMaximumSize(new java.awt.Dimension(1280, 768));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(1280, 768));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jDesktopPane1);

        javax.swing.GroupLayout content_PanelLayout = new javax.swing.GroupLayout(content_Panel);
        content_Panel.setLayout(content_PanelLayout);
        content_PanelLayout.setHorizontalGroup(
            content_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_PanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2)
                .addGap(0, 0, 0))
        );
        content_PanelLayout.setVerticalGroup(
            content_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_PanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout main_PanelLayout = new javax.swing.GroupLayout(main_Panel);
        main_Panel.setLayout(main_PanelLayout);
        main_PanelLayout.setHorizontalGroup(
            main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        main_PanelLayout.setVerticalGroup(
            main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(content_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_ItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_ItemMouseExited
        //     mouseExitedAnimation(search_Item);
        //  mouseExitedAnimation(search_Item_Icone);
    }//GEN-LAST:event_search_ItemMouseExited

    private void search_ItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_ItemMouseEntered
        //    mouseEnteredAnimation(search_Item);
        //  mouseEnteredAnimation(search_Item_Icone);
    }//GEN-LAST:event_search_ItemMouseEntered

    private void search_ItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_ItemMouseClicked
        //////////////////////////////
        jDesktopPane1.removeAll();
        Items_Details panel = new Items_Details();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_search_ItemMouseClicked

    private void add_New_ItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_New_ItemMouseExited
        // TODO add your handling code here:
        //   mouseExitedAnimation(add_New_Item);
        // mouseExitedAnimation(add_Item_Icon);
    }//GEN-LAST:event_add_New_ItemMouseExited

    private void add_New_ItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_New_ItemMouseEntered
        // TODO add your handling code here:
        //  mouseEnteredAnimation(add_New_Item);
        // mouseEnteredAnimation(add_Item_Icon);
    }//GEN-LAST:event_add_New_ItemMouseEntered

    private void add_New_ItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_New_ItemMouseClicked
        jDesktopPane1.removeAll();
        Add_New_Item panel = new Add_New_Item();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_add_New_ItemMouseClicked

    private void add_New_ItemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_add_New_ItemFocusGained
        //  add_New_Item.setForeground(Color.BLUE);
    }//GEN-LAST:event_add_New_ItemFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Setting Dashboard Panel To JDesktopPane1
        jDesktopPane1.removeAll();
        Pos_System_Frame panel = new Pos_System_Frame();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
        System.out.println(jDesktopPane1.getWidth() + "  " + jDesktopPane1.getHeight());
    }//GEN-LAST:event_formWindowOpened

    private void categories_DetailsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_categories_DetailsFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_categories_DetailsFocusGained

    private void categories_DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categories_DetailsMouseClicked
        jDesktopPane1.removeAll();
        Categories_Details panel = new Categories_Details();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_categories_DetailsMouseClicked

    private void categories_DetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categories_DetailsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_categories_DetailsMouseEntered

    private void categories_DetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categories_DetailsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_categories_DetailsMouseExited

    private void staff_DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staff_DetailsMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        Staff_Members_Details panel = new Staff_Members_Details();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_staff_DetailsMouseClicked

    private void staff_DetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staff_DetailsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_DetailsMouseEntered

    private void staff_DetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staff_DetailsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_DetailsMouseExited

    private void suppliers_DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliers_DetailsMouseClicked
        jDesktopPane1.removeAll();
        Suppliers_Details panel = new Suppliers_Details();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_suppliers_DetailsMouseClicked

    private void suppliers_DetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliers_DetailsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliers_DetailsMouseEntered

    private void suppliers_DetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliers_DetailsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliers_DetailsMouseExited

    private void companies_DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companies_DetailsMouseClicked
        jDesktopPane1.removeAll();
        Companies panel = new Companies();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_companies_DetailsMouseClicked

    private void companies_DetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companies_DetailsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_companies_DetailsMouseEntered

    private void companies_DetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companies_DetailsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_companies_DetailsMouseExited

    private void colours_DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colours_DetailsMouseClicked
        jDesktopPane1.removeAll();
        Colors_Details panel = new Colors_Details();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_colours_DetailsMouseClicked

    private void colours_DetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colours_DetailsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_colours_DetailsMouseEntered

    private void colours_DetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colours_DetailsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_colours_DetailsMouseExited

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        //

    }//GEN-LAST:event_formWindowStateChanged

    private void staff_AttendingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staff_AttendingMouseClicked
        jDesktopPane1.removeAll();
        Staff_Attending_Details panel = new Staff_Attending_Details();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_staff_AttendingMouseClicked

    private void staff_AttendingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staff_AttendingMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_AttendingMouseEntered

    private void staff_AttendingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staff_AttendingMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_AttendingMouseExited

    private void srtaff_Salary_PayingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_srtaff_Salary_PayingMouseClicked
        jDesktopPane1.removeAll();
        Staff_Salary_Paying panel = new Staff_Salary_Paying();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_srtaff_Salary_PayingMouseClicked

    private void srtaff_Salary_PayingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_srtaff_Salary_PayingMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_srtaff_Salary_PayingMouseEntered

    private void srtaff_Salary_PayingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_srtaff_Salary_PayingMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_srtaff_Salary_PayingMouseExited

    private void add_New_PhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_New_PhoneMouseClicked
        jDesktopPane1.removeAll();
        Add_New_Phone panel = new Add_New_Phone();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_add_New_PhoneMouseClicked

    private void add_New_PhoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_New_PhoneMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_add_New_PhoneMouseEntered

    private void add_New_PhoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_New_PhoneMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_add_New_PhoneMouseExited

    private void search_PhonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_PhonesMouseClicked
        jDesktopPane1.removeAll();
        Phone_Details panel = new Phone_Details();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_search_PhonesMouseClicked

    private void search_PhonesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_PhonesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_search_PhonesMouseEntered

    private void search_PhonesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_PhonesMouseExited
        /////////////////
    }//GEN-LAST:event_search_PhonesMouseExited

    private void sales_ReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sales_ReportMouseClicked
        jDesktopPane1.removeAll();
        Sales_Report panel = new Sales_Report();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_sales_ReportMouseClicked

    private void sales_ReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sales_ReportMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sales_ReportMouseEntered

    private void sales_ReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sales_ReportMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_sales_ReportMouseExited

    private void sales_ReturnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sales_ReturnsMouseClicked
        jDesktopPane1.removeAll();
        Sales.Sales_Returns panel = new Sales.Sales_Returns();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_sales_ReturnsMouseClicked

    private void sales_ReturnsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sales_ReturnsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sales_ReturnsMouseEntered

    private void sales_ReturnsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sales_ReturnsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_sales_ReturnsMouseExited

    private void pos_SystemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos_SystemMouseClicked
        jDesktopPane1.removeAll();
        Pos_System_Frame panel = new Pos_System_Frame();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_pos_SystemMouseClicked

    private void pos_SystemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos_SystemMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pos_SystemMouseEntered

    private void pos_SystemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos_SystemMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pos_SystemMouseExited

    private void GRN_ReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRN_ReportMouseClicked
        jDesktopPane1.removeAll();
        GRN_Report panel = new GRN_Report();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_GRN_ReportMouseClicked

    private void GRN_ReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRN_ReportMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_GRN_ReportMouseEntered

    private void GRN_ReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRN_ReportMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_GRN_ReportMouseExited

    private void stock_ReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_ReturnMouseClicked
        jDesktopPane1.removeAll();
        Stock_Returns panel = new Stock_Returns();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_stock_ReturnMouseClicked

    private void stock_ReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_ReturnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_stock_ReturnMouseEntered

    private void stock_ReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_ReturnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_stock_ReturnMouseExited

    private void add_new_GRNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_new_GRNMouseClicked
        jDesktopPane1.removeAll();
        New_GRN_Frame panel = new New_GRN_Frame();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_add_new_GRNMouseClicked

    private void add_new_GRNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_new_GRNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_add_new_GRNMouseEntered

    private void add_new_GRNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_new_GRNMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_add_new_GRNMouseExited

    private void sales_Returns_DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sales_Returns_DetailsMouseClicked
        jDesktopPane1.removeAll();
        Sales_Returns_Details panel = new Sales_Returns_Details();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_sales_Returns_DetailsMouseClicked

    private void sales_Returns_DetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sales_Returns_DetailsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sales_Returns_DetailsMouseEntered

    private void sales_Returns_DetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sales_Returns_DetailsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_sales_Returns_DetailsMouseExited

    private void stock_Returns_DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_Returns_DetailsMouseClicked
        jDesktopPane1.removeAll();
        Stock.Stock_Returns_Details panel = new Stock.Stock_Returns_Details();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_stock_Returns_DetailsMouseClicked

    private void stock_Returns_DetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_Returns_DetailsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_stock_Returns_DetailsMouseEntered

    private void stock_Returns_DetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_Returns_DetailsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_stock_Returns_DetailsMouseExited

    private void users_DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_users_DetailsMouseClicked
        jDesktopPane1.removeAll();
        Users_Details panel = new Users_Details();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_users_DetailsMouseClicked

    private void users_DetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_users_DetailsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_users_DetailsMouseEntered

    private void users_DetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_users_DetailsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_users_DetailsMouseExited

    private void jScrollPane1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane1ComponentAdded
        jScrollPane1.setUI(new WindowsScrollPaneUI());
    }//GEN-LAST:event_jScrollPane1ComponentAdded

    private void item_SizesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item_SizesMouseClicked
        jDesktopPane1.removeAll();
        Item_Sizes panel = new Item_Sizes();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_item_SizesMouseClicked

    private void item_SizesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item_SizesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_item_SizesMouseEntered

    private void item_SizesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item_SizesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_item_SizesMouseExited

    private void repairs_DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repairs_DetailsMouseClicked
        jDesktopPane1.removeAll();
        Repairs_Details panel = new Repairs_Details();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_repairs_DetailsMouseClicked

    private void repairs_DetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repairs_DetailsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_repairs_DetailsMouseEntered

    private void repairs_DetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repairs_DetailsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_repairs_DetailsMouseExited

    private void Stock_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_LabelMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        Stock_Frame panel = new Stock_Frame();
        panel.setSize(jDesktopPane1.getSize());
        panel.setVisible(true);
        jDesktopPane1.add(panel);
    }//GEN-LAST:event_Stock_LabelMouseClicked

    private void Stock_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_LabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Stock_LabelMouseEntered

    private void Stock_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stock_LabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Stock_LabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GRN_Report;
    private org.jdesktop.swingx.JXTaskPane GRN_task_Pane;
    private org.jdesktop.swingx.JXPanel Item_Panel;
    private javax.swing.JLabel Stock_Icon;
    private javax.swing.JLabel Stock_Label;
    private javax.swing.JLabel add_Item_Icon;
    private javax.swing.JLabel add_Item_Icon1;
    private javax.swing.JLabel add_New_Item;
    private javax.swing.JLabel add_New_Phone;
    private javax.swing.JLabel add_new_GRN;
    private javax.swing.JLabel categories_Details;
    private javax.swing.JLabel colours_Details;
    private javax.swing.JLabel companies_Details;
    private javax.swing.JPanel content_Panel;
    private javax.swing.JLabel item_Sizes;
    private org.jdesktop.swingx.JXTaskPane item_TaskPane;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel main_Panel;
    private javax.swing.JPanel menu_Panel;
    private org.jdesktop.swingx.JXPanel other_Panel;
    private org.jdesktop.swingx.JXPanel other_Panel1;
    private org.jdesktop.swingx.JXPanel other_Panel2;
    private org.jdesktop.swingx.JXPanel other_Panel3;
    private org.jdesktop.swingx.JXTaskPane other_Task_Pane;
    private javax.swing.JLabel pos_System;
    private javax.swing.JLabel repairs_Details;
    private javax.swing.JLabel sales_Report;
    private javax.swing.JLabel sales_Returns;
    private javax.swing.JLabel sales_Returns_Details;
    private org.jdesktop.swingx.JXTaskPane sales_task_Pane;
    private javax.swing.JLabel search_Item;
    private javax.swing.JLabel search_Item_Icone;
    private javax.swing.JLabel search_Item_Icone1;
    private javax.swing.JLabel search_Item_Icone10;
    private javax.swing.JLabel search_Item_Icone11;
    private javax.swing.JLabel search_Item_Icone12;
    private javax.swing.JLabel search_Item_Icone13;
    private javax.swing.JLabel search_Item_Icone14;
    private javax.swing.JLabel search_Item_Icone15;
    private javax.swing.JLabel search_Item_Icone16;
    private javax.swing.JLabel search_Item_Icone2;
    private javax.swing.JLabel search_Item_Icone3;
    private javax.swing.JLabel search_Item_Icone4;
    private javax.swing.JLabel search_Item_Icone5;
    private javax.swing.JLabel search_Item_Icone6;
    private javax.swing.JLabel search_Item_Icone7;
    private javax.swing.JLabel search_Item_Icone8;
    private javax.swing.JLabel search_Item_Icone9;
    private javax.swing.JLabel search_Phones;
    private javax.swing.JLabel srtaff_Salary_Paying;
    private javax.swing.JLabel staff_Attending;
    private javax.swing.JLabel staff_Details;
    private javax.swing.JLabel staff_Img;
    private javax.swing.JLabel staff_Img1;
    private javax.swing.JLabel staff_Img2;
    private org.jdesktop.swingx.JXTaskPane staff_Task_Pane;
    private javax.swing.JLabel stock_Return;
    private javax.swing.JLabel stock_Returns_Details;
    private javax.swing.JLabel suppliers_Details;
    private javax.swing.JLabel users_Details;
    // End of variables declaration//GEN-END:variables
private void mouseEnteredAnimation(JLabel label) {
        label.setOpaque(true);
        label.setBackground(new Color(51, 153, 255));
    }

    private void mouseExitedAnimation(JLabel label) {
        label.setOpaque(false);
        label.setBackground(new Color(51, 153, 255));
    }
}
